// A local bank of nice things the fish says now and then. Keep each short
// enough to fit a bubble (~140 chars). Add your own freely.
module.exports = [
  // --- gentle encouragement ---
  "you're doing better than you think 🌱",
  "one small step still counts as forward",
  "you've survived 100% of your hardest days",
  "progress, not perfection 🐟",
  "it's okay to rest — you're not a machine",
  "be proud of how far you've come",
  "you don't have to do it all today",
  "small wins are still wins ✨",
  "you're allowed to take up space",
  "future you is grateful for what you do now",
  "tiny consistent effort beats a big burnout",
  "you can do hard things",
  "done is better than perfect",
  "you're exactly where you need to be right now",
  "trust the process, even the slow parts",
  "your pace is the right pace",
  "you're growing even when it doesn't feel like it",
  "give yourself the kindness you give others",
  "it's brave to keep trying",
  "you matter more than your to-do list",

  // --- focus + work ---
  "deep breath. one thing at a time 🫧",
  "close the extra tabs — your brain will thank you",
  "what's the next tiny step? just that one",
  "save your work, swim on 🐟",
  "you can always start with a messy first draft",
  "momentum loves a 5-minute start",
  "protect your focus like it's treasure",
  "great work takes breaks too",
  "stuck? rubber-duck it to me 🦆",
  "ship it, then improve it",
  "your future self is watching — make 'em proud",
  "a clear desk is a clear mind",
  "you've got this next 25 minutes",
  "name the goal, then ignore everything else",
  "perfect is the enemy of shipped",

  // --- self-care reminders ---
  "have you had water recently? 💧",
  "blink. look at something far away for 20s 👀",
  "shoulders down, unclench your jaw 😌",
  "stretch those legs, friend 🦵",
  "stand up and wiggle — i'll wait",
  "breathe in for 4, out for 6 🫁",
  "snack? hydrate? quick walk?",
  "posture check! sit up tall",
  "your eyes deserve a screen break",
  "go get some sunlight if you can ☀️",
  "rest is productive too",
  "you can pause without guilt",
  "drink some water, you magnificent human 💧",
  "step outside for one fresh breath",

  // --- warmth + kindness ---
  "you're someone's reason to smile today",
  "the world is better with you in it 🌍",
  "you are enough, exactly as you are",
  "someone is glad you exist today",
  "be gentle with yourself today",
  "you deserve good things 🌷",
  "your feelings are valid",
  "it's okay to ask for help",
  "you're not behind, you're on your own path",
  "you bring something no one else can",
  "kindness counts — especially toward yourself",
  "you're worthy of rest and joy",

  // --- playful + fishy ---
  "blub blub 🐟 (that means hi)",
  "just keep swimming 🐠",
  "you and me against the current 🌊",
  "ten outta ten, would swim with you again",
  "i believe in you, human friend 🐟",
  "today's forecast: you, being awesome",
  "glub. that's fish for 'you rock' 🪨",
  "swimming through Monday like a champ",
  "be the calm fish in choppy water 🌊",
  "i'm just a little fish cheering you on 📣",
  "fin-tastic effort today 🐟",
  "o-fish-ally proud of you",
  "let it go like water off a fin 💦",
  "you're making waves (the good kind) 🌊",

  // --- perspective ---
  "this too shall pass 🌤️",
  "you can't pour from an empty cup",
  "comparison is the thief of joy",
  "what went well today? even one thing counts",
  "the bad days make the good ones brighter",
  "you're allowed to change your mind",
  "not every day has to be productive",
  "slow is smooth, smooth is fast",
  "you can begin again, any moment you like",
  "worry is interest paid on trouble before it's due",
  "you've got a whole ocean of time 🌊",
  "courage is just fear that said its prayers",
  "be where your feet are 🦶",
  "the only way out is through",

  // --- end of day ---
  "whatever you finished today is enough",
  "time to log off soon? 🌙",
  "you showed up today, and that matters",
  "rest well — tomorrow's a fresh tide 🌊",
  "close the laptop, you earned it",
  "good work today, genuinely",
  "wind down gently tonight 🌙",
  "you did your best with what you had",
];
